# Generated by Django 5.1.3 on 2025-08-29 03:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
                ("name", models.CharField(help_text="The artist name", max_length=100)),
            ],
            options={
                "ordering": ("name",),
                "indexes": [
                    models.Index(fields=["name"], name="rock_music__name_3df834_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
                ("name", models.CharField(help_text="The album name", max_length=100)),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="The year the album was released"
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        help_text="The artist that produced the album",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="rock_music_assignment.artist",
                    ),
                ),
            ],
            options={
                "ordering": ("artist", "year", "name"),
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
                ("name", models.CharField(help_text="The track name", max_length=100)),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="The track number on the album"
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        help_text="The album this track appears on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="rock_music_assignment.album",
                    ),
                ),
            ],
            options={
                "ordering": ("number", "name"),
            },
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["artist", "year", "name"], name="rock_music__artist__b9d308_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["number", "name"], name="rock_music__number_910d9f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                fields=("album", "number"), name="unique_album_number"
            ),
        ),
    ]
