# Generated by Django 5.1.3 on 2025-09-18 06:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rock_music_assignment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="name of the playlist", max_length=256),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlayListTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="specifies the order of the track in the playlist"
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        help_text="playlist id in playlist track to identify the playlist",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rock_music_assignment.playlist",
                    ),
                ),
                (
                    "track_id",
                    models.ForeignKey(
                        help_text="track id in playlist",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rock_music_assignment.track",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="playlist",
            name="tracks",
            field=models.ManyToManyField(
                related_name="playlist_tracks",
                through="rock_music_assignment.PlayListTrack",
                to="rock_music_assignment.track",
            ),
        ),
        migrations.AddConstraint(
            model_name="playlisttrack",
            constraint=models.UniqueConstraint(
                fields=("order", "playlist_id", "track_id"),
                name="unique_track_order_in_playlist",
            ),
        ),
    ]
